---
# Basic site settings
title: Civic Tech Waterloo Region
email: civictechwr@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Civic Tech Waterloo Region is a community group that brings together people
  from different sectors and industries to actively solve issues facing our
  local community using technology-based solutions.
baseurl: "" # The subpath of your site, e.g., /blog
url: "" # The base URL of your site

# Socials
slack_invite: https://join.slack.com/t/civictechwr/shared_invite/zt-2hk4c93hv-DEIbxR_z1xKj8cZmayVHTw
instagram: https://instagram.com/civictechwr
meetup: https://luma.com/civictechwr
twitter: https://twitter.com/civictechwr
facebook: https://facebook.com/civictechwr

# Exclusions
exclude:
  - ".sass-cache"
  - ".jekyll-cache"
  - "node_modules"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor"
  - "README.md"
  - "LICENSE.txt"
  - "docs"
  - "scripts"
  - "eslint.config.js"
  - ".stylelintrc.json"
  - ".htmlhintrc"
  - "package.json"
  - "package-lock.json"
  - ".gitignore"
  - ".cursorrules"
  - ".cursorignore"
  - "*.min.js.map"

# Includes
include:
  - ".htaccess"
  - "css/*.min.css"
  - "js/*.min.js"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: America/Toronto

# Keep files
keep_files:
  - css/*.min.css
  - js/*.min.js

# Performance optimizations
incremental: true
future: false
unpublished: false

# Collections
collections:
  projects:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "CivicTechWR"
      comments: false
      share: false
      read_time: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
seo:
  type: "Organization"
  name: "Civic Tech Waterloo Region"
  description: "Community group bringing together people to solve local issues
    using technology"
  url: "https://civictechwr.org"
  logo: "/images/logos/civictechwr_logo_black.png"
  same_as:
    - "https://twitter.com/civictechwr"
    - "https://facebook.com/civictechwr"
    - "https://instagram.com/civictechwr"
    - "https://www.linkedin.com/company/civictechwr"
